# image will be published to ghcr.io/<user>/<name>
name: blue-stetson
# description will be included in the image's metadata
description: My personal silverblue image. Probably no use for anybody else...

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      # - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      # Vorerst nicht. Wenn ich etwas Zeit habe, die Fehler zu analysieren.
      # - https://repo.protonvpn.com/fedora-41-stable/protonvpn-stable-release/protonvpn-stable-release-1.0.2-1.noarch.rpm
    install:
      # - proton-vpn-gnome-desktop
      # s.o.
      - xorg-x11-nvidia
      - fastfetch
      - fastfetch-bash-completion
      - distrobox
      - yt-dlp
      - yt-dlp-bash-completion
      - pwgen
      - gnome-extensions-app
    remove:
      - ublue-os-update-services
      - ublue-os-just
      - just
      - gnome-classic-session
      - gnome-shell-extension-background-logo
      - gnome-shell-extension-supergfxctl-gex
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list
      # Vorerst nicht:
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
    install:  
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

